# Generated by Django 5.2.4 on 2026-01-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auth_type",
            field=models.CharField(
                choices=[("system", "System"), ("google", "Google")],
                default="system",
                max_length=20,
            ),
        ),
    ]
