# Generated by Django 5.2.4 on 2025-09-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_loginactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginActivity',
        ),
    ]
