# Generated by Django 5.2.4 on 2025-08-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='original_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
