# Generated by Django 5.2.4 on 2025-08-03 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('contactnumber', models.CharField(max_length=10)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='provider_profiles/')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('jobtype', models.CharField(max_length=20)),
                ('joineddate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
