# Generated by Django 5.2.4 on 2025-08-06 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerdetails',
            name='jobtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='providerdetails',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='media/ProvidersPictures/'),
        ),
    ]
