# Generated by Django 5.2.4 on 2025-08-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('userprofile', '0002_alter_providerdetails_jobtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerdetails',
            name='jobtype',
        ),
        migrations.AddField(
            model_name='providerdetails',
            name='jobtype',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
