# Generated by Django 5.2.4 on 2025-08-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_providerdetails_jobtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerdetails',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
