# Generated by Django 5.2.4 on 2025-08-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_providerdetails_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerdetails',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='ProvidersPictures/'),
        ),
    ]
