# Generated by Django 5.2.4 on 2025-09-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_providerdetails_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerdetails',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
