# Generated by Django 5.2.4 on 2025-09-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_providerdetails_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerdetails',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
