# Generated by Django 5.2.4 on 2026-01-12 16:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0007_providerdetails_rating_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="providerdetails",
            name="profilepic",
        ),
        migrations.AddField(
            model_name="providerdetails",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                default=32, max_length=255, verbose_name="image"
            ),
            preserve_default=False,
        ),
    ]
