# Generated by Django 5.2.4 on 2026-01-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0008_remove_providerdetails_profilepic_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="providerdetails",
            old_name="profile_image",
            new_name="profilepic",
        ),
    ]
