# Generated by Django 5.2.4 on 2025-08-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Booking_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
