# Generated by Django 5.2.4 on 2025-08-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_booking_time_notification_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='Booking_time',
        ),
        migrations.AddField(
            model_name='notification',
            name='booking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
