# Generated by Django 5.2.4 on 2025-08-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
