# Generated by Django 5.2.4 on 2025-08-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
