# Generated by Django 5.2.4 on 2025-08-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
