# Generated by Django 5.2.4 on 2025-08-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField()),
                ('original_price', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False)),
                ('features', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
